version: '3'

networks:
  bluesky-services_bluesky:
    external: true
services:
  dastard:
    image: ${NBS_IMAGE_REG:-ghcr.io/xraygui/nbs-pods/}microcal-daq
    volumes:
      - /tmp/.dastard:/root/.dastard
      - /tmp/data:/data
    networks:
      - bluesky-services_bluesky
    command: bash -c "source /root/daq/bin/activate; dastard"

  # bahama:
  #   image: microcal-daq
  #   volumes:
  #     - /tmp/.dastard:/root/.dastard
  #     - /tmp/data:/data
  #     - ${HOME}/work/dastard:/usr/local/src/dastard
  #   command: >
  #     bash -c "tail -f /dev/null && cd /usr/local/src/dastard/cmd/bahama && 
  #       go run bahama.go --host dastard
  #     "
  #   networks:
  #     - bluesky-services_bluesky
  #   depends_on:
  #     dastard:
  #       condition: service_started
  #

  tes-server:
    image: microcal-daq
    volumes:
      - /tmp/data:/data
      - /tmp/.scan_server:/root/.scan_server
      - ${HOME}/work/nsls-ii-sst/tes-ioc:/root/tes-ioc
    command: >
      bash -c "
        tail -f /dev/null &&
        pip3 install -e /usr/local/src/nsls-ii-sst/tes_scan_server &&
        nsls_server /usr/local/share/ipython/profile_default/startup/tes_server.toml
      "
    networks:
      - bluesky-services_bluesky
