[configuration]
baseline = ['motors', 'shutters', 'mirrors', 'manipulators']
has_slits = true
has_motorized_samples = true
has_motorized_eref = true

[devices]
i0 = { threshold = 0.1, description = "Gold Mesh" }
i1 = { threshold = 0.15, description = "Back Dioide" }
sc = { threshold = 0.1 }
ref = { threshold = 0.1 }
ucal_sc = { activate = false }
psh7 = { default = true }
ring_current = { baseline = true }
adr = { baseline = true }

[detectors.alignment]
indirect = "i1"
direct = "sc"

[detectors_sets.default]
primary = ["sc", "tes"]
normalization = "i0"
reference = "ref"

[settings]
startup_modules = ["nbs_bl.startup", "ucal.startup"]
tes_processing = "/nsls2/data/sst/shared/config/ucal/processing_status"
beamline = "sst1"


[settings.plans]
xas = ["regions.toml", "/home/xf07id1/Public/regions.toml"]

[settings.redis.md]
host = "xf07id1-nexafs-redis1.nsls2.bnl.gov"
port=6380
ssl=true


[settings.redis.info]
host = "xf07id1-nexafs-redis1.nsls2.bnl.gov"
port=6380
ssl=true
db=1

[settings.tiled_writer]
enabled = true
profile = "nsls2"
api_key_env = "TILED_BLUESKY_WRITING_API_KEY_NEXAFS"
catalog_path = ["ucal", "raw"]
subscribe_method = "post_document"

[settings.kafka]
name = "nexafs"